---
services:
  ombi:
    image: lscr.io/linuxserver/ombi:latest
    container_name: ombi
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Chicago
      - BASE_URL=/ombi #optional
    volumes:
      - /config:/config
    ports:
      - 80:80
    restart: unless-stopped
